config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    namespace :billing do
      get 'billing_arrangements/index'
      get 'billing_arrangements/edit'
    end
  end
  namespace :admin do
  namespace :billing do
    get 'credit_memos/index'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'credit_memos/edit'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'cc_transactions/index'
    end
  end

  namespace :admin do
    
    namespace :billing do
      post 'email_invoice' => 'invoices#email'
      post 'invoices_print_batch' => 'invoices#print_batch'
      post 'invoices_email_batch' => 'invoices#email_batch'
      post 'invoices_update_status_batch' => 'invoices#update_status_batch'
      
			resources :billing_arrangements do 
				member do
					get 'update_prices'
				end
			end
      resources :cc_transactions
      resources :service_types
      resources :packages do
        member do
          get 'details' => 'packages#details'
          post 'details' => 'packages#update_details'
        end
      end
      resources :package_details
      resources :user_packages do
        member do
          get 'services'
          get 'add_service'
        end
      end
      resources :user_services
      resources :payment_methods
      resources :invoices do 
        member do 
          get 'print'
          post 'email'
        end
      end
      resources :credit_memos do 
        member do 
          get 'print'
        end
      end
      resources :payments do 
        member do
          get 'refund'
        end
      end
    end
    
  end
  
  namespace :account do
    resources :user_packages
    resources :payments
    resources :payment_methods do
      member do 
        get 'primary'
      end
    end
  end
  
end

app/controllers/admin/billing/billing_arrangements_controller.rb
class Admin::Billing::BillingArrangementsController < Admin::BaseController

  def index
    authorize BillingArrangement.new
    @billing_arrangements = BillingArrangement.includes(:affiliate, :seller).order(created_at: :desc)

    respond_to do |format|
      format.html { @billing_arrangements = @billing_arrangements.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data BillingArrangement.to_csv(@billing_arrangements) }
    end
  end

  def new
    @billing_arrangement = authorize BillingArrangement.new
    render 'edit'
  end

  def create
    @billing_arrangement = authorize BillingArrangement.new(billing_arrangement_params)

    if @billing_arrangement.save
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def show
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def edit
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def update
    @billing_arrangement = authorize BillingArrangement.find(params[:id])

    if @billing_arrangement.update(billing_arrangement_params)
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def destroy
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
    @billing_arrangement.destroy

    flash[:notice] = "Billing Arrangement has been deleted."
    redirect_back fallback_location: {action: 'index'}
  end

  def update_prices
    @billing_arrangement = BillingArrangement.find(params[:id])

    ap_list = AffiliateProduct.joins(:product)
                  .where(affiliate_id: @billing_arrangement.seller_id)
                  .where("store_products.fulfiller_id = ?", @billing_arrangement.affiliate_id)

    if @billing_arrangement.percent_of_msrp
      count = ap_list.update_all("store_affiliate_products.price = store_products.msrp * #{@billing_arrangement.percent_of_msrp / 100.0}")
    else
      count = ap_list.update_all("store_affiliate_products.price = store_products.reseller_price")
    end

    flash[:info] = "Pricing updated."
    redirect_to action: :show, id: @billing_arrangement.id
  end

  private

  def billing_arrangement_params
    params.require(:billing_arrangement).permit!
  end

end

app/controllers/admin/billing/cc_transactions_controller.rb
class Admin::Billing::CcTransactionsController < Admin::BaseController

  def index
    authorize CcTransaction.new
    @cc_transactions = CcTransaction.joins(:payment_method)
                           .includes(:payment_method)
                           .order(sort_column + " " + sort_direction)

    @cc_transactions = @cc_transactions.where("created_at > '#{params[:start_date]}'") unless params[:start_date].blank?
    @cc_transactions = @cc_transactions.where("created_at < '#{params[:end_date]}'") unless params[:end_date].blank?

    respond_to do |format|
      format.html { @cc_transactions = @cc_transactions.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data CcTransaction.to_csv(@cc_transactions) }
    end

  end

  def show
    @cc_transaction = authorize CcTransaction.find(params[:id])
  end


  private

  def sort_column
    params[:sort] || "bill_cc_transactions.created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/controllers/admin/billing/credit_memos_controller.rb
class Admin::Billing::CreditMemosController < Admin::BaseController
  def index
    authorize CreditMemo.new
    @credit_memos = CreditMemo.order(created_at: :desc)
                        .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @credit_memo = authorize CreditMemo.new
    render 'edit'
  end

  def create
    @credit_memo = authorize CreditMemo.new(credit_memo_params)

    if @credit_memo.save
      redirect_to action: 'index', notice: 'Credit Memo was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def edit
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def update
    @credit_memo = authorize CreditMemo.find(params[:id])

    if @credit_memo.update(credit_memo_params)
      redirect_to action: 'index', notice: 'Credit Memo was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    cm = authorize CreditMemo.find(params[:id])
    cm.destroy
    redirect_to action: 'index', notice: 'Credit Memo has been deleted.'
  end

  def print
    @credit_memo = CreditMemo.find(params[:id])
    authorize @credit_memo, :show?
    render 'print', layout: nil
  end


  private

  def credit_memo_params
    params.require(:credit_memo).permit!
  end

end

app/controllers/admin/billing/invoices_controller.rb
class Admin::Billing::InvoicesController < Admin::BaseController

  def index
    authorize Invoice.new
    @invoices = Invoice.where(paid: params[:paid])
                    .order(post_date: :desc)
                    .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    if params[:affiliate_id]
      @pending_payments = Payment.where(affiliate_id: params[:affiliate_id], invoice_id: nil)
                              .where.not(payable_type: :invoice)
    end

    @invoice = Invoice.new
    5.times { @invoice.payments.build }

    authorize @invoice
    render 'edit'
  end

  def create
    @invoice = authorize Invoice.new(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @invoice.items.length + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully created.'
    else
      5.times { @invoice.payments.build }
      render 'edit'
    end
  end

  def edit
    @invoice = authorize Invoice.find(params[:id])
    @pending_payments = Payment.where(invoice_id: @invoice.id)
                            .where.not(payable_type: :invoice)

    2.times { @invoice.payments.build }
  end

  def update
    @invoice = authorize Invoice.find(params[:id])
    item_count = @invoice.payments.length

    @invoice.assign_attributes(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save(validate: false)
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @invoice = authorize Invoice.find(params[:id])
  end

  def print
    @invoice = Invoice.find(params[:id])
    render 'print', layout: nil
  end

  def print_batch
    authorize Invoice, :show?

    urls = ''
    token = Cache.setting(Rails.configuration.domain_id, :system, 'Security Token')
    website_url = Cache.setting(Rails.configuration.domain_id, :system, 'Website URL')

    Invoice.where(id: params[:invoice_id]).each do |inv|
      digest = Digest::MD5.hexdigest(inv.id.to_s + token)
      urls += " " + website_url + print_admin_billing_invoice_path(inv, digest: digest)

      # LOG HERE
      inv.logs.create(timestamp: Time.now,
                      user_id: session[:user_id],
                      ip_address: request.remote_ip,
                      event: :printed,
                      data1: params[:printer_id].presence || 'PDF download')
    end

    output_file = "/tmp/#{SecureRandom.hex(6)}.pdf"
    ret = system("wkhtmltopdf -q -s Letter #{urls} #{output_file}")

    #puts ">>>>>>>> " + urls

    unless File.exist?(output_file)
      flash[:error] = "Unable to generate PDF [Debug: #{$?}]"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:printer_id].blank?
      send_file output_file
    else
      printer = Printer.find(params[:printer_id])
      job = printer.print_file(output_file)
      flash[:info] = "Print job submitted to '#{printer.name} [#{printer.location}]'. CUPS JobID: #{job.id}"
      redirect_back(fallback_location: admin_billing_invoices_path)
    end
  end

  def email
    @invoice = Invoice.find(params[:invoice_id])

    EmailInvoiceJob.perform_later(@invoice.id, params[:email])
    @invoice.logs.create(user_id: session[:user_id], ip_address: request.remote_ip, event: 'emailed', data1: params[:email])

    flash[:info] = "Invoice ##{@invoice.id} has been emailed to #{params[:email]}"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def email_batch

    if params[:email_address].blank?
      flash[:error] = "Please specify an email address"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:invoice_id].length == 0
      flash[:error] = "Please invoices to email"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    begin
      InvoiceMailer.batch(params[:invoice_id], session[:user_id], params[:email_address], request.remote_ip).deliver_now
      flash[:success] = "#{params[:invoice_id].length} invoice(s) were mailed to '#{params[:email_address]}'"
    rescue => e
      flash[:error] = e.message
    end

    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  def update_status_batch
    authorize Invoice, :update?
    list = Invoice.where(id: params[:invoice_id])

    list.each do |invoice|
      invoice.update(paid: params[:paid] == "true")
      #log
    end

    flash[:info] = "#{list.length} invoices updated"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def destroy
    @invoice = authorize Invoice.find(params[:id])

    Payment.where(invoice_id: @invoice.id).update_all(invoice_id: nil)
    @invoice.destroy

    flash.now[:success] = "Invoice ##{@invoice.id} has been deleted"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  private

  def invoice_params
    params.require(:invoice).permit!
  end

end

app/controllers/admin/billing/package_details_controller.rb
class Admin::Billing::PackageDetailsController < Admin::BaseController

  def new
    @package_detail = PackageDetail.new package_id: params[:package_id]
    render 'edit'
  end

  def create
    @package_detail = PackageDetail.new(package_detail_params)

    if @package_detail.save
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def edit
    @package_detail = PackageDetail.find(params[:id])
  end

  def update
    @package_detail = PackageDetail.find(params[:id])

    if @package_detail.update(package_detail_params)
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def destroy
    @package_detail = PackageDetail.find(params[:id])
    @package_detail.destroy
    redirect_to action: 'index', notice: 'Package detail has been deleted.'
  end

  def details
    @package = PackageDetail.find(params[:id])
  end


  private

  def package_detail_params
    params.require(:package_detail).permit!
  end

end

app/controllers/admin/billing/packages_controller.rb
class Admin::Billing::PackagesController < Admin::BaseController

  def index
    authorize Package.new
    @packages = Package.where(domain_id: cookies[:domain_id])

    respond_to do |format|
      format.html { @packages = @packages.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Package.to_csv(@packages) }
    end
  end

  def new
    @package = authorize Package.new(name: 'New Package', sort: 9, trial_days: 0)
    render 'edit'
  end

  def create
    @package = authorize Package.new(package_params)
    @package.domain_id = cookies[:domain_id]

    if @package.save
      redirect_to action: 'index', notice: 'Package was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @package = authorize Package.includes(:details, [details: :service_type]).find(params[:id])
  end

  def edit
    @package = authorize Package.find(params[:id])
  end

  def update
    @package = authorize Package.find(params[:id])

    if @package.update(package_params)
      redirect_to action: 'index', notice: 'Package was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @package = authorize Package.find(params[:id])
    @package.destroy
    redirect_to action: 'index', notice: 'Package has been deleted.'
  end


  def details
    @package = Package.find(params[:id])
    authorize @package, :show?
  end


  private

  def package_params
    params.require(:package).permit!
  end

end

app/controllers/admin/billing/payment_methods_controller.rb
class Admin::Billing::PaymentMethodsController < Admin::BaseController

  def index
    authorize PaymentMethod.new
    @payment_methods = PaymentMethod.includes(:user)

    respond_to do |format|
      format.html { @payment_methods = @payment_methods.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data PaymentMethod.to_csv(@payment_methods) }
    end
  end

  def show
    @payment_method = authorize PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = authorize PaymentMethod.new(user_id: params[:user_id])
  end

  def create
    @payment_method = authorize PaymentMethod.new(payment_method_params)
    @payment_method.status = 'A'

    if @payment_method.save
      flash[:notice] = 'Payment Method was successfully created.'
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def destroy
    pm = authorize PaymentMethod.find(params[:id])
    pm.destroy

    # if there is only one remaining payment_method, make it the default
    if PaymentMethod.where(user_id: pm.user_id).count == 1
      PaymentMethod.where(user_id: pm_user_id).update_all(default: true)
    end

    redirect_to action: 'index'
  end


  private

  def payment_method_params
    params.require(:payment_method).permit!
  end

end

app/controllers/admin/billing/service_types_controller.rb
class Admin::Billing::ServiceTypesController < Admin::BaseController

  def index
    authorize ServiceType.new
    @service_types = ServiceType.where(domain_id: cookies[:domain_id]).order(:sort)

    respond_to do |format|
      format.html { @service_types = @service_types.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data ServiceType.to_csv(@service_types) }
    end
  end

  def new
    @service_type = authorize ServiceType.new(name: 'New service type')
    render 'edit'
  end

  def create
    @service_type = authorize ServiceType.new(service_type_params)
    @service_type.domain_id = cookies[:domain_id]

    if @service_type.save
      redirect_to action: 'index', notice: 'Service Type was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @service_type = authorize ServiceType.find(params[:id])
  end

  def edit
    @service_type = authorize ServiceType.find(params[:id])
  end

  def update
    @service_type = authorize ServiceType.find(params[:id])

    if @service_type.update(service_type_params)
      redirect_to action: 'index', notice: 'Service Type was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @service_type = authorize ServiceType.find(params[:id])
    @service_type.destroy
    redirect_to action: 'index', notice: 'Service Type has been deleted.'
  end


  private

  def service_type_params
    params.require(:service_type).permit!
  end

end

app/helpers/admin/billing/billing_arrangements_helper.rb
module Admin::Billing::BillingArrangementsHelper
end

app/views/admin/billing/billing_arrangements/_billing_arrangement.html.erb
<tr>
  <td><%= link_to billing_arrangement.id.to_s, admin_billing_billing_arrangement_path(billing_arrangement) %></td>
  <td><%= link_to billing_arrangement.affiliate.name, admin_system_affiliate_path(billing_arrangement.affiliate, q: :billing_arrangements) %></td>
  <td><%= link_to billing_arrangement.seller.name, admin_system_affiliate_path(billing_arrangement.seller, q: :billing_arrangements) %></td>
  <td><%= number_to_currency(billing_arrangement.dropshipper_transaction_fee) %></td>
  <td>
    <%= number_to_currency(billing_arrangement.seller_transaction_fee) %>
    <% if billing_arrangement.seller_transaction_percent %>
      + <%= billing_arrangement.seller_transaction_percent %>% COGS
    <% end %>
  </td>
  <td><%= billing_arrangement.percent_of_msrp ? "#{billing_arrangement.percent_of_msrp.to_i}%" : "n.a" %></td>
  <td class="text-center"><%= tick billing_arrangement.invoice_seller %></td>
  <td><%= sysdate billing_arrangement.created_at %></td>
  <td class="text-right">
    <%= link_to "edit", edit_admin_billing_billing_arrangement_path(billing_arrangement) %> &nbsp;
    <%= link_to "delete",
                {action: "destroy", id: billing_arrangement.id},
                method: :delete,
                data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/admin/billing/billing_arrangements/edit.html.erb
<h2><%= @billing_arrangement %></h2>
<hr>

<%= simple_form_for [:admin, :billing, @billing_arrangement] do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>

  <%= f.association :affiliate, collection: Cache.affiliate_list('dropshippers') %>
  <%= f.association :seller, collection: Affiliate.where(active: true).order(:name) %>
  <%= f.input :percent_of_msrp %>
  <%= f.input :dropshipper_transaction_fee %>
  <%= f.input :seller_transaction_fee %>
  <%= f.input :seller_transaction_percent %>
  <%= f.input :uses_seller_shipping_account %>
  <%= f.input :invoice_seller %>

  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>



<% content_for :title, "Billing Arrangement" %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to "Billing Arrangements", admin_billing_billing_arrangements_path %></li>
  <li class="active"><%= @billing_arrangement.persisted? ? "edit" : "new" %></li>
<% end %>

app/views/admin/billing/billing_arrangements/index.html.erb
<%= link_to new_admin_billing_billing_arrangement_path, class: 'btn btn-sm btn-default pull-right' do %>
  <i class="fa fa-edit"></i> New arrangement
<% end %>
<h2><i class="fa fa-project-diagram"></i> Billing Arrangements</h2>
<hr>

<table class="table table-striped table-condensed">
  <tr>
    <th>ID
    </td>
    <th>Dropshipper</th>
    <th>Seller</th>
    <th>Dropshipper Fee</th>
    <th>Seller Fee</th>
    <th>Percent of MSRP</th>
    <th class="text-center">Invoice Seller?</th>
    <th>Created</th>
    <th>&nbsp;</th>
  </tr>
  <%= render @billing_arrangements %>
</table>

<%= render 'admin/shared/table_summary', data: @billing_arrangements %>


<% content_for :title, "Billing Arrangements" %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li class="active">Billing Arrangements</li>
<% end %>

app/views/admin/billing/billing_arrangements/show.html.erb
<h2>
  <%= link_to "edit", edit_admin_billing_billing_arrangement_path(@billing_arrangement), class: "btn btn-sm btn-default pull-right" %>
  <h2><i class="fa fa-project-diagram"></i> Billing Arrangement: <%= @billing_arrangement.id %></h2>
  <hr/>

  <div class="col-md-6">
    <table class="table table-condensed table-bordered summary">
      <tr>
        <th></th>
        <th>Entity</th>
        <th>Cost = % MSRP</th>
        <th>Transaction Fee</th>
      </tr>
      <tr>
        <td>Seller</td>
        <td><%= link_to @billing_arrangement.seller.name, admin_system_affiliate_path(@billing_arrangement.seller, q: :billing_arrangements) %></td>
        <td><%= @billing_arrangement.percent_of_msrp ? "#{@billing_arrangement.percent_of_msrp.to_i}%" : "Reseller Price" %></td>
        <td>
          <%= number_to_currency(@billing_arrangement.seller_transaction_fee) %>
          <% if @billing_arrangement.seller_transaction_percent %>
            + <%= @billing_arrangement.seller_transaction_percent %>% COGS
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Dropshipper</td>
        <td><%= link_to @billing_arrangement.affiliate.name, admin_system_affiliate_path(@billing_arrangement.affiliate, q: :billing_arrangements) %></td>
        <td>n/a</td>
        <td><%= number_to_currency(@billing_arrangement.dropshipper_transaction_fee) %></td>
      </tr>
    </table>
  </div>


  <%
    ap_list = AffiliateProduct.includes(product: :pictures)
        .joins(:product)
        .where(affiliate_id: @billing_arrangement.seller_id)
        .where("store_products.fulfiller_id = ?", @billing_arrangement.affiliate_id)
        .sample(5)
  %>

  <div class="col-md-12">
    <h3>Example seller fees</h3>

    <% if ap_list.length > 0 %>
      <table class="table table-bordered">
        <tr>
          <th></th>
          <th>Item</th>
          <th class="text-right">MSRP</th>
          <th class="text-right">Calculated COGS</th>
          <th class="text-right">COGS in DB</th>
          <th class="text-right">Transaction Fees</th>
        </tr>
        <% ap_list.each do |ap|
          fees = @billing_arrangement.seller_transaction_fee
          if @billing_arrangement.seller_transaction_percent
            fees += ap.product.negotiated_price(@billing_arrangement.seller_id) * @billing_arrangement.seller_transaction_percent / 100.0
          end

          if ap.product.pictures.any?
            file_path = ap.product.pictures[0].file_path
          else
            file_path = "/images/no-image.png"
          end
        %>
          <tr>
            <td>
        <span class="order-item-thumbnail hidden-print">
          <a href="<%= cdn_image_url file_path, 800, 700, 0 %>" data-lightbox="image-1">
            <img src="<%= cdn_image_url file_path, 50, 50, 2 %>" title="product" height="50"/>
          </a>
        </span>
            </td>
            <td><%= link_to ap.product.name, admin_store_product_path(ap.product_id) %><br><%= ap.product.item_number %>
            </td>
            <td class="text-right"><%= number_to_currency(ap.product.msrp) %></td>
            <td class="text-right"><%= number_to_currency(ap.product.negotiated_price(@billing_arrangement.seller_id)) %></td>
            <td class="text-right"><%= number_to_currency(ap.price) %></td>
            <td class="text-right"><%= number_to_currency(fees) %></td>
          </tr>
        <% end %>
      </table>

      <%= link_to update_prices_admin_billing_billing_arrangement_path(@billing_arrangement), class: "btn btn-sm btn-default" do %>
        <i class="fa fa-sync-alt"></i> Update Prices
      <% end %>

    <% else %>
      <div class="alert alert-warning">There are no products loaded</div>
    <% end %>
  </div>






  <%= content_for :title do %>
    Billing Arrangement: <%= @billing_arrangement.id %>
  <% end %>


  <% content_for :menu do
    render "admin/shared/billing_menu"
  end %>


  <% content_for :breadcrumbs do %>
    <li><a href="#">Billing</a></li>
    <li><%= link_to "Billing Arrangements", admin_billing_billing_arrangements_path %></li>
    <li class="active"><%= @billing_arrangement.id %></li>
  <% end %>