config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    namespace :billing do
      get 'billing_arrangements/index'
      get 'billing_arrangements/edit'
    end
  end
  namespace :admin do
  namespace :billing do
    get 'credit_memos/index'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'credit_memos/edit'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'cc_transactions/index'
    end
  end

  namespace :admin do
    
    namespace :billing do
      post 'email_invoice' => 'invoices#email'
      post 'invoices_print_batch' => 'invoices#print_batch'
      post 'invoices_email_batch' => 'invoices#email_batch'
      post 'invoices_update_status_batch' => 'invoices#update_status_batch'
      
			resources :billing_arrangements do 
				member do
					get 'update_prices'
				end
			end
      resources :cc_transactions
      resources :service_types
      resources :packages do
        member do
          get 'details' => 'packages#details'
          post 'details' => 'packages#update_details'
        end
      end
      resources :package_details
      resources :user_packages do
        member do
          get 'services'
          get 'add_service'
        end
      end
      resources :user_services
      resources :payment_methods
      resources :invoices do 
        member do 
          get 'print'
          post 'email'
        end
      end
      resources :credit_memos do 
        member do 
          get 'print'
        end
      end
      resources :payments do 
        member do
          get 'refund'
        end
      end
    end
    
  end
  
  namespace :account do
    resources :user_packages
    resources :payments
    resources :payment_methods do
      member do 
        get 'primary'
      end
    end
  end
  
end

app/controllers/account/payment_methods_controller.rb
class Account::PaymentMethodsController < Account::BaseController

  def index
    @payment_methods = PaymentMethod.where(user_id: session[:user_id]).order(created_at: :desc)
  end

  def new
    @payment_method = PaymentMethod.new
  end

  def create
    @payment_method = PaymentMethod.new(payment_method_params)
    @payment_method.user_id = session[:user_id]
    @payment_method.status = 'A'

    # if this is only one payment_method, make it the default
    if PaymentMethod.where(user_id: session[:user_id]).count == 0
      @payment_method.default = true
    end

    @payment_method.save

    respond_to do |format|
      format.html do
        if @payment_method.errors.any?
          render 'new'
        else
          flash[:notice] = 'Payment method was successfully saved.'
          redirect_to action: 'index'
        end
      end
      format.js { render :layout => false }
    end
  end

  def destroy
    @payment_method = PaymentMethod.find_by(id: params[:id], user_id: session[:user_id])
    @payment_method.destroy

    # if there is only one remaining payment_method, make it the default
    if PaymentMethod.where(user_id: session[:user_id]).count == 1
      PaymentMethod.where(user_id: session[:user_id]).update_all(default: true)
    end

    respond_to do |format|
      format.html do
        flash[:notice] = 'Payment method has been removed.'
        redirect_to action: 'index'
      end
      format.js { render :layout => false }
    end
  end

  def primary
    PaymentMethod.where(user_id: session[:user_id]).update_all(default: false)
    PaymentMethod.where(user_id: session[:user_id], id: params[:id]).update_all(default: true)

    redirect_back(fallback_location: account_payment_methods)
  end


  private

  def payment_method_params
    params.require(:payment_method).permit(:cardholder_name, :number, :expiration_month, :expiration_year, :expiration,
                                           :billing_street1, :billing_street2, :billing_city, :billing_state,
                                           :billing_zip, :billing_country)
  end

end

app/controllers/admin/billing/billing_arrangements_controller.rb
class Admin::Billing::BillingArrangementsController < Admin::BaseController

  def index
    authorize BillingArrangement.new
    @billing_arrangements = BillingArrangement.includes(:affiliate, :seller).order(created_at: :desc)

    respond_to do |format|
      format.html { @billing_arrangements = @billing_arrangements.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data BillingArrangement.to_csv(@billing_arrangements) }
    end
  end

  def new
    @billing_arrangement = authorize BillingArrangement.new
    render 'edit'
  end

  def create
    @billing_arrangement = authorize BillingArrangement.new(billing_arrangement_params)

    if @billing_arrangement.save
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def show
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def edit
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def update
    @billing_arrangement = authorize BillingArrangement.find(params[:id])

    if @billing_arrangement.update(billing_arrangement_params)
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def destroy
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
    @billing_arrangement.destroy

    flash[:notice] = "Billing Arrangement has been deleted."
    redirect_back fallback_location: {action: 'index'}
  end

  def update_prices
    @billing_arrangement = BillingArrangement.find(params[:id])

    ap_list = AffiliateProduct.joins(:product)
                  .where(affiliate_id: @billing_arrangement.seller_id)
                  .where("store_products.fulfiller_id = ?", @billing_arrangement.affiliate_id)

    if @billing_arrangement.percent_of_msrp
      count = ap_list.update_all("store_affiliate_products.price = store_products.msrp * #{@billing_arrangement.percent_of_msrp / 100.0}")
    else
      count = ap_list.update_all("store_affiliate_products.price = store_products.reseller_price")
    end

    flash[:info] = "Pricing updated."
    redirect_to action: :show, id: @billing_arrangement.id
  end

  private

  def billing_arrangement_params
    params.require(:billing_arrangement).permit!
  end

end

app/controllers/admin/billing/cc_transactions_controller.rb
class Admin::Billing::CcTransactionsController < Admin::BaseController

  def index
    authorize CcTransaction.new
    @cc_transactions = CcTransaction.joins(:payment_method)
                           .includes(:payment_method)
                           .order(sort_column + " " + sort_direction)

    @cc_transactions = @cc_transactions.where("created_at > '#{params[:start_date]}'") unless params[:start_date].blank?
    @cc_transactions = @cc_transactions.where("created_at < '#{params[:end_date]}'") unless params[:end_date].blank?

    respond_to do |format|
      format.html { @cc_transactions = @cc_transactions.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data CcTransaction.to_csv(@cc_transactions) }
    end

  end

  def show
    @cc_transaction = authorize CcTransaction.find(params[:id])
  end


  private

  def sort_column
    params[:sort] || "bill_cc_transactions.created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/controllers/admin/billing/credit_memos_controller.rb
class Admin::Billing::CreditMemosController < Admin::BaseController
  def index
    authorize CreditMemo.new
    @credit_memos = CreditMemo.order(created_at: :desc)
                        .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @credit_memo = authorize CreditMemo.new
    render 'edit'
  end

  def create
    @credit_memo = authorize CreditMemo.new(credit_memo_params)

    if @credit_memo.save
      redirect_to action: 'index', notice: 'Credit Memo was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def edit
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def update
    @credit_memo = authorize CreditMemo.find(params[:id])

    if @credit_memo.update(credit_memo_params)
      redirect_to action: 'index', notice: 'Credit Memo was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    cm = authorize CreditMemo.find(params[:id])
    cm.destroy
    redirect_to action: 'index', notice: 'Credit Memo has been deleted.'
  end

  def print
    @credit_memo = CreditMemo.find(params[:id])
    authorize @credit_memo, :show?
    render 'print', layout: nil
  end


  private

  def credit_memo_params
    params.require(:credit_memo).permit!
  end

end

app/controllers/admin/billing/invoices_controller.rb
class Admin::Billing::InvoicesController < Admin::BaseController

  def index
    authorize Invoice.new
    @invoices = Invoice.where(paid: params[:paid])
                    .order(post_date: :desc)
                    .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    if params[:affiliate_id]
      @pending_payments = Payment.where(affiliate_id: params[:affiliate_id], invoice_id: nil)
                              .where.not(payable_type: :invoice)
    end

    @invoice = Invoice.new
    5.times { @invoice.payments.build }

    authorize @invoice
    render 'edit'
  end

  def create
    @invoice = authorize Invoice.new(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @invoice.items.length + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully created.'
    else
      5.times { @invoice.payments.build }
      render 'edit'
    end
  end

  def edit
    @invoice = authorize Invoice.find(params[:id])
    @pending_payments = Payment.where(invoice_id: @invoice.id)
                            .where.not(payable_type: :invoice)

    2.times { @invoice.payments.build }
  end

  def update
    @invoice = authorize Invoice.find(params[:id])
    item_count = @invoice.payments.length

    @invoice.assign_attributes(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save(validate: false)
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @invoice = authorize Invoice.find(params[:id])
  end

  def print
    @invoice = Invoice.find(params[:id])
    render 'print', layout: nil
  end

  def print_batch
    authorize Invoice, :show?

    urls = ''
    token = Cache.setting(Rails.configuration.domain_id, :system, 'Security Token')
    website_url = Cache.setting(Rails.configuration.domain_id, :system, 'Website URL')

    Invoice.where(id: params[:invoice_id]).each do |inv|
      digest = Digest::MD5.hexdigest(inv.id.to_s + token)
      urls += " " + website_url + print_admin_billing_invoice_path(inv, digest: digest)

      # LOG HERE
      inv.logs.create(timestamp: Time.now,
                      user_id: session[:user_id],
                      ip_address: request.remote_ip,
                      event: :printed,
                      data1: params[:printer_id].presence || 'PDF download')
    end

    output_file = "/tmp/#{SecureRandom.hex(6)}.pdf"
    ret = system("wkhtmltopdf -q -s Letter #{urls} #{output_file}")

    #puts ">>>>>>>> " + urls

    unless File.exist?(output_file)
      flash[:error] = "Unable to generate PDF [Debug: #{$?}]"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:printer_id].blank?
      send_file output_file
    else
      printer = Printer.find(params[:printer_id])
      job = printer.print_file(output_file)
      flash[:info] = "Print job submitted to '#{printer.name} [#{printer.location}]'. CUPS JobID: #{job.id}"
      redirect_back(fallback_location: admin_billing_invoices_path)
    end
  end

  def email
    @invoice = Invoice.find(params[:invoice_id])

    EmailInvoiceJob.perform_later(@invoice.id, params[:email])
    @invoice.logs.create(user_id: session[:user_id], ip_address: request.remote_ip, event: 'emailed', data1: params[:email])

    flash[:info] = "Invoice ##{@invoice.id} has been emailed to #{params[:email]}"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def email_batch

    if params[:email_address].blank?
      flash[:error] = "Please specify an email address"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:invoice_id].length == 0
      flash[:error] = "Please invoices to email"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    begin
      InvoiceMailer.batch(params[:invoice_id], session[:user_id], params[:email_address], request.remote_ip).deliver_now
      flash[:success] = "#{params[:invoice_id].length} invoice(s) were mailed to '#{params[:email_address]}'"
    rescue => e
      flash[:error] = e.message
    end

    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  def update_status_batch
    authorize Invoice, :update?
    list = Invoice.where(id: params[:invoice_id])

    list.each do |invoice|
      invoice.update(paid: params[:paid] == "true")
      #log
    end

    flash[:info] = "#{list.length} invoices updated"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def destroy
    @invoice = authorize Invoice.find(params[:id])

    Payment.where(invoice_id: @invoice.id).update_all(invoice_id: nil)
    @invoice.destroy

    flash.now[:success] = "Invoice ##{@invoice.id} has been deleted"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  private

  def invoice_params
    params.require(:invoice).permit!
  end

end

app/controllers/admin/billing/package_details_controller.rb
class Admin::Billing::PackageDetailsController < Admin::BaseController

  def new
    @package_detail = PackageDetail.new package_id: params[:package_id]
    render 'edit'
  end

  def create
    @package_detail = PackageDetail.new(package_detail_params)

    if @package_detail.save
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def edit
    @package_detail = PackageDetail.find(params[:id])
  end

  def update
    @package_detail = PackageDetail.find(params[:id])

    if @package_detail.update(package_detail_params)
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def destroy
    @package_detail = PackageDetail.find(params[:id])
    @package_detail.destroy
    redirect_to action: 'index', notice: 'Package detail has been deleted.'
  end

  def details
    @package = PackageDetail.find(params[:id])
  end


  private

  def package_detail_params
    params.require(:package_detail).permit!
  end

end

app/controllers/admin/billing/packages_controller.rb
class Admin::Billing::PackagesController < Admin::BaseController

  def index
    authorize Package.new
    @packages = Package.where(domain_id: cookies[:domain_id])

    respond_to do |format|
      format.html { @packages = @packages.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Package.to_csv(@packages) }
    end
  end

  def new
    @package = authorize Package.new(name: 'New Package', sort: 9, trial_days: 0)
    render 'edit'
  end

  def create
    @package = authorize Package.new(package_params)
    @package.domain_id = cookies[:domain_id]

    if @package.save
      redirect_to action: 'index', notice: 'Package was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @package = authorize Package.includes(:details, [details: :service_type]).find(params[:id])
  end

  def edit
    @package = authorize Package.find(params[:id])
  end

  def update
    @package = authorize Package.find(params[:id])

    if @package.update(package_params)
      redirect_to action: 'index', notice: 'Package was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @package = authorize Package.find(params[:id])
    @package.destroy
    redirect_to action: 'index', notice: 'Package has been deleted.'
  end


  def details
    @package = Package.find(params[:id])
    authorize @package, :show?
  end


  private

  def package_params
    params.require(:package).permit!
  end

end

app/controllers/admin/billing/user_services_controller.rb
class Admin::Billing::UserServicesController < Admin::BaseController

  def new
    @user_service = UserService.new user_package_id: params[:user_package_id]
    render 'edit'
  end

  def create
    @user_service = UserService.new(user_service_params)

    if @user_service.save
      redirect_to services_admin_billing_user_package_path(@user_service.user_package_id)
    else
      render 'edit'
    end
  end

  def edit
    @user_service = UserService.find(params[:id])
  end

  def update
    @user_service = UserService.find(params[:id])

    if @user_service.update(user_service_params)
      redirect_to services_admin_billing_user_package_path(@user_service.user_package_id)
    else
      render 'edit'
    end
  end

  def destroy
    @user_service = UserService.find(params[:id])
    @user_service.destroy
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def user_service_params
    params.require(:user_service).permit!
  end

end

app/helpers/admin/billing/billing_arrangements_helper.rb
module Admin::Billing::BillingArrangementsHelper
end

app/views/admin/billing/payment_methods/index.html.erb
<%= link_to new_admin_billing_payment_method_path, class: 'btn btn-sm btn-default pull-right' do %>
  <i class="fa fa-plus"></i> New credit card
<% end %>
<h2><i class="fa fa-credit-card"></i> &nbsp;Payment Methods</h2>

<table class="table table-striped table-condensed">
  <tr>
    <th>ID</th>
    <th>Card Holder</th>
    <th>Number</th>
    <th>Brand</th>
    <th>Expiration</th>
    <th>Last Transaction</th>
    <th>Result</th>
    <th class="text-center">Attempts</th>
    <th class="text-center">Default ?</th>
    <th class="text-center">Status</th>
    <th>&nbsp;</th>
  </tr>
  <% @payment_methods.each do |pm| %>
    <tr>
      <td><%= link_to pm.id.to_s, admin_billing_payment_method_path(pm) %></td>
      <td><%= link_to pm.cardholder_name, admin_system_user_path(pm.user_id) %></td>
      <td><%= pm.card_display %></td>
      <td><%= pm.card_brand.titlecase %></td>
      <td><%= pm.expiration_month %>/<%= pm.expiration_year %></td>
      <td>
        <% if pm.last_transaction_date %>
          <%= systime pm.last_transaction_date %>
        <% else %>
          -
        <% end %>
      </td>
      <td><%= pm.last_transaction_result %></td>
      <td class="text-center"><%= pm.bill_attempts %></td>
      <td class="text-center"><%= tick pm.default %></td>
      <td class="text-center"><%= pm.status %></td>
      <td>
        <%= link_to "delete",
                    {action: "destroy", id: pm.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @payment_methods %>


<% content_for :title do %>
  Payment Methods
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li class="active">Payment Methods</li>
<% end %>

app/views/admin/billing/payment_methods/new.html.erb
<h2>Credit Card</h2>
<hr/>

<%= simple_form_for [:admin, :billing, @payment_method] do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>

  <div class="row">
    <div class="col-md-6">
      <%= f.association :user %>
      <%= f.input :number, placeholder: '####-####-####-####', label: 'Number' %>
      <%= f.input :cardholder_name, label: "Cardholder" %>
      <div class="form-group string optional payment_method_billing_street1">
        <label class="string optional control-label col-sm-3" for="payment_method_billing_street1">Expiration</label>
        <div class="col-sm-9">
          <%= f.select :expiration_month, (1..12) %>
          <%= f.select :expiration_year, (2015..2025) %>
        </div>
      </div>
      <%= f.input :default %>
    </div>

    <div class="col-md-6">
      <%= f.input :billing_street1 %>
      <%= f.input :billing_street2 %>
      <%= f.input :billing_city %>
      <%= f.input :billing_state %>
      <%= f.input :billing_zip %>
      <%= f.input :billing_country %>
    </div>
  </div>

  <div class="col-md-12">
    <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>
  </div>
<% end %>



<% content_for :title do %>
  <%= @payment_method.card_display %>
<% end %>


<% content_for :menu do
  render "admin/shared/billing_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to "Payment Methods", admin_billing_payment_methods_path %></li>
  <li class="active"><%= @payment_method.card_display %></li>
<% end %>

app/views/admin/billing/payment_methods/show.html.erb
<h2>
  <%= link_to "edit", edit_admin_billing_payment_method_path(@payment_method), class: "btn btn-sm btn-default pull-right" %>
  <i class="icon-credit-card"></i> &nbsp;<%= @payment_method.card_display %></h2>
<hr/>


<div class="well row" style="margin-left: 0;">

  <div class="col-md-5">
    <div>
      <label>Card Holder:</label>
      <%= link_to @payment_method.cardholder_name, admin_system_user_path(@payment_method.user) %>
    </div>
    <div>
      <label>Brand:</label>
      <%= @payment_method.card_brand.titlecase %>
    </div>
    <div>
      <label>Number:</label>
      <%= @payment_method.card_display %>
    </div>
    <div>
      <label>Expiration:</label>
      <%= @payment_method.expiration_month %> / <%= @payment_method.expiration_year %>
    </div>
  </div>

  <div class="col-md-6">
    <div>
      <label style="height: 50px;">Billing:</label>
      <%= @payment_method.billing_street1 %><br/>
      <% unless @payment_method.billing_street2.blank? %>
        <%= @payment_method.billing_street2 %><br/>
      <% end %>
      <%= @payment_method.billing_city %>, <%= @payment_method.billing_state %> <%= @payment_method.billing_zip %><br/>
      <%= @payment_method.billing_country %>
    </div>
    <div>
      <label>Status:</label>
      <%= @payment_method.status %>
    </div>
    <% unless @payment_method.last_transaction_date.nil? %>
      <div>
        <label>Last Transaction:</label>
        <%= @payment_method.last_transaction_date %>
      </div>
    <% end %>
  </div>
</div>


<h4>Payments</h4>
<table class="table table-striped table-condensed">
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>User</th>
    <th>Item</th>
    <th>Memo</th>
    <th>Debit</th>
    <th>Credit</th>
  </tr>
  <% @payment_method.payments.order('created_at DESC').each do |payment| %>
    <tr>
      <td><%= payment.id %></td>
      <td><%= systime payment.created_at %></td>
      <td>
        <% if payment.user_id %>
          <%= link_to payment.user.name, admin_system_user_path(payment.user) %>
        <% else %>
          - guest -
        <% end %>
      </td>
      <td>
        <% if payment.payable_type == "order" %>
          <%= link_to "Order ##{payment.payable_id}", admin_store_order_path(payment.payable_id) %>
        <% elsif payment.payable_type == "UserPackage" %>
          <%= link_to UserPackage.find(payment.payable_id).package.name + " package [#{payment.payable_id}]", admin_billing_user_package_path(payment.payable_id) %>
        <% elsif payment.payable_type == "shipment" %>
          <% shipment = Shipment.find_by(id: payment.payable_id) %>
          <%= link_to "Shipment #{shipment}", admin_store_shipment_path(payment.payable_id) %>
        <% end %>
      </td>
      <td><%= payment.memo %></td>
      <td><%= number_to_currency(payment.amount) if payment.amount < 0.0 %></td>
      <td><%= number_to_currency(payment.amount) if payment.amount >= 0.0 %></td>
    </tr>
  <% end %>
</table>


<%= content_for :head do %>
  <style>
      .well label {
          float: left;
          width: 120px;
          text-align: right;
          font-weight: bold;
          padding-right: 12px;
      }

      .well div div {
          clear: left;
      }
  </style>
<% end %>


<%= content_for :title do %>
  <%= @payment_method.card_display %>
<% end %>


<% content_for :menu do
  render "admin/shared/billing_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to "Payment Methods", admin_billing_payment_methods_path %></li>
  <li class="active"><%= @payment_method %></li>
<% end %>