config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    namespace :billing do
      get 'billing_arrangements/index'
      get 'billing_arrangements/edit'
    end
  end
  namespace :admin do
  namespace :billing do
    get 'credit_memos/index'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'credit_memos/edit'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'cc_transactions/index'
    end
  end

  namespace :admin do
    
    namespace :billing do
      post 'email_invoice' => 'invoices#email'
      post 'invoices_print_batch' => 'invoices#print_batch'
      post 'invoices_email_batch' => 'invoices#email_batch'
      post 'invoices_update_status_batch' => 'invoices#update_status_batch'
      
			resources :billing_arrangements do 
				member do
					get 'update_prices'
				end
			end
      resources :cc_transactions
      resources :service_types
      resources :packages do
        member do
          get 'details' => 'packages#details'
          post 'details' => 'packages#update_details'
        end
      end
      resources :package_details
      resources :user_packages do
        member do
          get 'services'
          get 'add_service'
        end
      end
      resources :user_services
      resources :payment_methods
      resources :invoices do 
        member do 
          get 'print'
          post 'email'
        end
      end
      resources :credit_memos do 
        member do 
          get 'print'
        end
      end
      resources :payments do 
        member do
          get 'refund'
        end
      end
    end
    
  end
  
  namespace :account do
    resources :user_packages
    resources :payments
    resources :payment_methods do
      member do 
        get 'primary'
      end
    end
  end
  
end

app/controllers/admin/billing/billing_arrangements_controller.rb
class Admin::Billing::BillingArrangementsController < Admin::BaseController

  def index
    authorize BillingArrangement.new
    @billing_arrangements = BillingArrangement.includes(:affiliate, :seller).order(created_at: :desc)

    respond_to do |format|
      format.html { @billing_arrangements = @billing_arrangements.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data BillingArrangement.to_csv(@billing_arrangements) }
    end
  end

  def new
    @billing_arrangement = authorize BillingArrangement.new
    render 'edit'
  end

  def create
    @billing_arrangement = authorize BillingArrangement.new(billing_arrangement_params)

    if @billing_arrangement.save
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def show
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def edit
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def update
    @billing_arrangement = authorize BillingArrangement.find(params[:id])

    if @billing_arrangement.update(billing_arrangement_params)
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def destroy
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
    @billing_arrangement.destroy

    flash[:notice] = "Billing Arrangement has been deleted."
    redirect_back fallback_location: {action: 'index'}
  end

  def update_prices
    @billing_arrangement = BillingArrangement.find(params[:id])

    ap_list = AffiliateProduct.joins(:product)
                  .where(affiliate_id: @billing_arrangement.seller_id)
                  .where("store_products.fulfiller_id = ?", @billing_arrangement.affiliate_id)

    if @billing_arrangement.percent_of_msrp
      count = ap_list.update_all("store_affiliate_products.price = store_products.msrp * #{@billing_arrangement.percent_of_msrp / 100.0}")
    else
      count = ap_list.update_all("store_affiliate_products.price = store_products.reseller_price")
    end

    flash[:info] = "Pricing updated."
    redirect_to action: :show, id: @billing_arrangement.id
  end

  private

  def billing_arrangement_params
    params.require(:billing_arrangement).permit!
  end

end

app/controllers/admin/billing/cc_transactions_controller.rb
class Admin::Billing::CcTransactionsController < Admin::BaseController

  def index
    authorize CcTransaction.new
    @cc_transactions = CcTransaction.joins(:payment_method)
                           .includes(:payment_method)
                           .order(sort_column + " " + sort_direction)

    @cc_transactions = @cc_transactions.where("created_at > '#{params[:start_date]}'") unless params[:start_date].blank?
    @cc_transactions = @cc_transactions.where("created_at < '#{params[:end_date]}'") unless params[:end_date].blank?

    respond_to do |format|
      format.html { @cc_transactions = @cc_transactions.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data CcTransaction.to_csv(@cc_transactions) }
    end

  end

  def show
    @cc_transaction = authorize CcTransaction.find(params[:id])
  end


  private

  def sort_column
    params[:sort] || "bill_cc_transactions.created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/controllers/admin/billing/credit_memos_controller.rb
class Admin::Billing::CreditMemosController < Admin::BaseController
  def index
    authorize CreditMemo.new
    @credit_memos = CreditMemo.order(created_at: :desc)
                        .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @credit_memo = authorize CreditMemo.new
    render 'edit'
  end

  def create
    @credit_memo = authorize CreditMemo.new(credit_memo_params)

    if @credit_memo.save
      redirect_to action: 'index', notice: 'Credit Memo was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def edit
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def update
    @credit_memo = authorize CreditMemo.find(params[:id])

    if @credit_memo.update(credit_memo_params)
      redirect_to action: 'index', notice: 'Credit Memo was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    cm = authorize CreditMemo.find(params[:id])
    cm.destroy
    redirect_to action: 'index', notice: 'Credit Memo has been deleted.'
  end

  def print
    @credit_memo = CreditMemo.find(params[:id])
    authorize @credit_memo, :show?
    render 'print', layout: nil
  end


  private

  def credit_memo_params
    params.require(:credit_memo).permit!
  end

end

app/controllers/admin/billing/invoices_controller.rb
class Admin::Billing::InvoicesController < Admin::BaseController

  def index
    authorize Invoice.new
    @invoices = Invoice.where(paid: params[:paid])
                    .order(post_date: :desc)
                    .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    if params[:affiliate_id]
      @pending_payments = Payment.where(affiliate_id: params[:affiliate_id], invoice_id: nil)
                              .where.not(payable_type: :invoice)
    end

    @invoice = Invoice.new
    5.times { @invoice.payments.build }

    authorize @invoice
    render 'edit'
  end

  def create
    @invoice = authorize Invoice.new(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @invoice.items.length + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully created.'
    else
      5.times { @invoice.payments.build }
      render 'edit'
    end
  end

  def edit
    @invoice = authorize Invoice.find(params[:id])
    @pending_payments = Payment.where(invoice_id: @invoice.id)
                            .where.not(payable_type: :invoice)

    2.times { @invoice.payments.build }
  end

  def update
    @invoice = authorize Invoice.find(params[:id])
    item_count = @invoice.payments.length

    @invoice.assign_attributes(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save(validate: false)
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @invoice = authorize Invoice.find(params[:id])
  end

  def print
    @invoice = Invoice.find(params[:id])
    render 'print', layout: nil
  end

  def print_batch
    authorize Invoice, :show?

    urls = ''
    token = Cache.setting(Rails.configuration.domain_id, :system, 'Security Token')
    website_url = Cache.setting(Rails.configuration.domain_id, :system, 'Website URL')

    Invoice.where(id: params[:invoice_id]).each do |inv|
      digest = Digest::MD5.hexdigest(inv.id.to_s + token)
      urls += " " + website_url + print_admin_billing_invoice_path(inv, digest: digest)

      # LOG HERE
      inv.logs.create(timestamp: Time.now,
                      user_id: session[:user_id],
                      ip_address: request.remote_ip,
                      event: :printed,
                      data1: params[:printer_id].presence || 'PDF download')
    end

    output_file = "/tmp/#{SecureRandom.hex(6)}.pdf"
    ret = system("wkhtmltopdf -q -s Letter #{urls} #{output_file}")

    #puts ">>>>>>>> " + urls

    unless File.exist?(output_file)
      flash[:error] = "Unable to generate PDF [Debug: #{$?}]"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:printer_id].blank?
      send_file output_file
    else
      printer = Printer.find(params[:printer_id])
      job = printer.print_file(output_file)
      flash[:info] = "Print job submitted to '#{printer.name} [#{printer.location}]'. CUPS JobID: #{job.id}"
      redirect_back(fallback_location: admin_billing_invoices_path)
    end
  end

  def email
    @invoice = Invoice.find(params[:invoice_id])

    EmailInvoiceJob.perform_later(@invoice.id, params[:email])
    @invoice.logs.create(user_id: session[:user_id], ip_address: request.remote_ip, event: 'emailed', data1: params[:email])

    flash[:info] = "Invoice ##{@invoice.id} has been emailed to #{params[:email]}"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def email_batch

    if params[:email_address].blank?
      flash[:error] = "Please specify an email address"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:invoice_id].length == 0
      flash[:error] = "Please invoices to email"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    begin
      InvoiceMailer.batch(params[:invoice_id], session[:user_id], params[:email_address], request.remote_ip).deliver_now
      flash[:success] = "#{params[:invoice_id].length} invoice(s) were mailed to '#{params[:email_address]}'"
    rescue => e
      flash[:error] = e.message
    end

    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  def update_status_batch
    authorize Invoice, :update?
    list = Invoice.where(id: params[:invoice_id])

    list.each do |invoice|
      invoice.update(paid: params[:paid] == "true")
      #log
    end

    flash[:info] = "#{list.length} invoices updated"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def destroy
    @invoice = authorize Invoice.find(params[:id])

    Payment.where(invoice_id: @invoice.id).update_all(invoice_id: nil)
    @invoice.destroy

    flash.now[:success] = "Invoice ##{@invoice.id} has been deleted"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  private

  def invoice_params
    params.require(:invoice).permit!
  end

end

app/controllers/admin/billing/package_details_controller.rb
class Admin::Billing::PackageDetailsController < Admin::BaseController

  def new
    @package_detail = PackageDetail.new package_id: params[:package_id]
    render 'edit'
  end

  def create
    @package_detail = PackageDetail.new(package_detail_params)

    if @package_detail.save
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def edit
    @package_detail = PackageDetail.find(params[:id])
  end

  def update
    @package_detail = PackageDetail.find(params[:id])

    if @package_detail.update(package_detail_params)
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def destroy
    @package_detail = PackageDetail.find(params[:id])
    @package_detail.destroy
    redirect_to action: 'index', notice: 'Package detail has been deleted.'
  end

  def details
    @package = PackageDetail.find(params[:id])
  end


  private

  def package_detail_params
    params.require(:package_detail).permit!
  end

end

app/controllers/admin/billing/packages_controller.rb
class Admin::Billing::PackagesController < Admin::BaseController

  def index
    authorize Package.new
    @packages = Package.where(domain_id: cookies[:domain_id])

    respond_to do |format|
      format.html { @packages = @packages.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Package.to_csv(@packages) }
    end
  end

  def new
    @package = authorize Package.new(name: 'New Package', sort: 9, trial_days: 0)
    render 'edit'
  end

  def create
    @package = authorize Package.new(package_params)
    @package.domain_id = cookies[:domain_id]

    if @package.save
      redirect_to action: 'index', notice: 'Package was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @package = authorize Package.includes(:details, [details: :service_type]).find(params[:id])
  end

  def edit
    @package = authorize Package.find(params[:id])
  end

  def update
    @package = authorize Package.find(params[:id])

    if @package.update(package_params)
      redirect_to action: 'index', notice: 'Package was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @package = authorize Package.find(params[:id])
    @package.destroy
    redirect_to action: 'index', notice: 'Package has been deleted.'
  end


  def details
    @package = Package.find(params[:id])
    authorize @package, :show?
  end


  private

  def package_params
    params.require(:package).permit!
  end

end

app/controllers/admin/billing/payment_methods_controller.rb
class Admin::Billing::PaymentMethodsController < Admin::BaseController

  def index
    authorize PaymentMethod.new
    @payment_methods = PaymentMethod.includes(:user)

    respond_to do |format|
      format.html { @payment_methods = @payment_methods.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data PaymentMethod.to_csv(@payment_methods) }
    end
  end

  def show
    @payment_method = authorize PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = authorize PaymentMethod.new(user_id: params[:user_id])
  end

  def create
    @payment_method = authorize PaymentMethod.new(payment_method_params)
    @payment_method.status = 'A'

    if @payment_method.save
      flash[:notice] = 'Payment Method was successfully created.'
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def destroy
    pm = authorize PaymentMethod.find(params[:id])
    pm.destroy

    # if there is only one remaining payment_method, make it the default
    if PaymentMethod.where(user_id: pm.user_id).count == 1
      PaymentMethod.where(user_id: pm_user_id).update_all(default: true)
    end

    redirect_to action: 'index'
  end


  private

  def payment_method_params
    params.require(:payment_method).permit!
  end

end

app/controllers/admin/billing/service_types_controller.rb
class Admin::Billing::ServiceTypesController < Admin::BaseController

  def index
    authorize ServiceType.new
    @service_types = ServiceType.where(domain_id: cookies[:domain_id]).order(:sort)

    respond_to do |format|
      format.html { @service_types = @service_types.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data ServiceType.to_csv(@service_types) }
    end
  end

  def new
    @service_type = authorize ServiceType.new(name: 'New service type')
    render 'edit'
  end

  def create
    @service_type = authorize ServiceType.new(service_type_params)
    @service_type.domain_id = cookies[:domain_id]

    if @service_type.save
      redirect_to action: 'index', notice: 'Service Type was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @service_type = authorize ServiceType.find(params[:id])
  end

  def edit
    @service_type = authorize ServiceType.find(params[:id])
  end

  def update
    @service_type = authorize ServiceType.find(params[:id])

    if @service_type.update(service_type_params)
      redirect_to action: 'index', notice: 'Service Type was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @service_type = authorize ServiceType.find(params[:id])
    @service_type.destroy
    redirect_to action: 'index', notice: 'Service Type has been deleted.'
  end


  private

  def service_type_params
    params.require(:service_type).permit!
  end

end

app/helpers/admin/billing/billing_arrangements_helper.rb
module Admin::Billing::BillingArrangementsHelper
end

app/views/admin/billing/invoices/_group_actions.html.erb
<form action="" method="get" style="display: none;">
  <input type="hidden" name="uid" value="<%= params[:uid] %>">
  <input type="text" name="start_date" class="date-field" value="<%= params[:start_date] %>"> to
  <input type="textbox" name="end_date" class="date-field" value="<%= params[:end_date] %>">
  <input type="submit" class="btn btn-sm btn-default">
</form>

<div class="pull-right hidden-xs">
  <select id="selAction" class="form-control" style="display: inline; width: 75%">
    <option> - - Select Action - -</option>
    <option method="get" value="<%= new_admin_billing_invoice_path %>">New invoice</option>
    <option method="post" print-dialog="true" print-format="pdf" value="<%= admin_billing_invoices_print_batch_path %>">Print
      (PDF)
    </option>
    <option method="post" email-dialog="true" value="<%= admin_billing_invoices_email_batch_path %>">Email invoices
    </option>
    <optgroup label="Mark as ">
      <option method="post" value="<%= admin_billing_invoices_update_status_batch_path(paid: "true") %>">Paid</option>
      <option method="post" value="<%= admin_billing_invoices_update_status_batch_path(paid: "false") %>">Unpaid</option>
    </optgroup>
  </select>
  <input type="button" class="btn btn-default btn-small" id="btnAction" value="Go"/>
</div>

app/views/admin/billing/invoices/_invoice.html.erb
<tr>
  <td><input type="checkbox" name="invoice_id[]" class="multiselect hidden-xs" value="<%= invoice.id %>"/></td>
  <td><%= link_to invoice.id.to_s, admin_billing_invoice_path(invoice) %></td>
  <td><%= invoice.post_date ? sysdate(invoice.post_date) : '<span class="light">- not posted -</span>'.html_safe %></td>
  <td><%= link_to invoice.from_affiliate, admin_system_affiliate_path(invoice.from_affiliate) %></td>
  <td><%= link_to_user_or_affiliate invoice, :invoices %></td>
  <td class="text-right"><%= number_to_currency invoice.amount %></td>
  <td class="text-center"><%= invoice.due_date %></td>
  <td class="text-center">
    <% if invoice.paid %>
      <span class="label label-success">paid</span>
    <% elsif invoice.due_date && (invoice.due_date < Date.today) %>
      <span class="label label-danger">overdue</span>
    <% else %>
      <span class="label label-warning">unpaid</span>
    <% end %>
  </td>
  <td class="text-right">
    <%= link_to "edit", edit_admin_billing_invoice_path(invoice) %> &nbsp;
    <%= link_to "delete",
                {controller: 'admin/billing/invoices', action: "destroy", id: invoice.id},
                method: :delete,
                data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/admin/billing/invoices/edit.html.erb
<h2>
  <% if @invoice.persisted? %>
    Invoice #<%= @invoice.id %>
  <% else %>
    New Invoice
  <% end %>
  <br>
  <small><%= link_to_user_or_affiliate @invoice %></small>
</h2>
<hr>

<%= render 'admin/shared/error_messages', object: @invoice %>

<%= simple_form_for [:admin, :billing, @invoice] do |f| %>

  <input type="hidden" name="add_more_items" value=""/>
  <div class="row">

    <div class="col-md-6">
      <div class="panel panel-success">
        <div class="panel-heading">
          <%= link_to "update amount", "#", class: 'update-invoice pull-right' %>
          Invoice:
        </div>
        <div class="panel-body">
          <%= f.association :from_affiliate, label: 'Issued by' %>
          <%= f.association :affiliate, label: 'Issued to' %>
          <%= f.input :amount %>
          <%= f.input :post_date, as: :datepicker %>
          <%= f.input :due_date, as: :datepicker %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Notes:</div>
        <div class="panel-body">
          <%= f.input :note, input_html: {class: '', rows: 2} %>
          <%= f.input :paid %>
        </div>
      </div>

      <div class="pull-right">
        <%= link_to '$ update total amount', '#', class: 'update-amount btn btn-default btn-sm' %>
        <%= link_to '+ add more items', '#', class: 'add-more-items btn btn-default btn-sm' %>
      </div>
    </div>

  </div>


  <h3>Add Payments</h3>
  <table class="table table-striped table-condensed table-bordered">
    <tr>
      <th>Memo</th>
      <th>Transaction ID</th>
      <th>Amount</th>
      <th>&nbsp;</th>
    </tr>
    <%= f.simple_fields_for :payments do |itemf| %>
      <%
        item = @invoice.payments[itemf.index]
      %>
      <tr>
        <td><%= itemf.input_field :memo, style: "width: 100%" %></td>
        <td width="150"><%= itemf.input_field :transaction_id %></td>
        <td width="150"><%= itemf.input_field :amount %></td>
        <td width="30">
          <i class="fa fa-times light"></i>
          <%= itemf.hidden_field :_destroy, class: 'destroy' %>
          <%= itemf.hidden_field :payable_id %>
          <%= itemf.hidden_field :payable_type %>
        </td>
      </tr>
    <% end %>
  </table>


  <% if defined?(@pending_payments) && @pending_payments.length > 0 %>
    <h3>Invoice Items</h3>
    <table class="table table-striped table-condensed table-bordered">
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>User / Affiliate</th>
        <th>Item</th>
        <th>Transaction ID
        </td>
        <th>Method</th>
        <th>Memo</th>
        <th class="text-right">Amount</th>
      </tr>
      <%= render partial: "admin/billing/payments/payment", collection: @pending_payments %>
      <tr>
        <td class="text-right" colspan="7"><b>Total:</b></td>
        <td class="text-right">
          <b><%= number_to_currency(@pending_payments.sum(&:amount), negative_format: "(%u%n)") %></b></td>
      </tr>
    </table>
  <% end %>



  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>



<% content_for :title do %>
  Invoice #<%= @invoice.id %>
<% end %>


<% content_for :head do %>
  <style>
      .form-inline .form-group {
          margin: 10px 0;
      }

      .fa-times {
          cursor: pointer;
      }

      .bold {
          font-weight: bold;
      }
  </style>

  <script>
      $(document).ready(function () {

          $(".update-amount").click(function (e) {

              e.preventDefault();
              var total = 0.0;

              $(".quantity").each(function () {
                  var unit_price = parseFloat($(this).parent().parent().find(".unit-price").val());
                  var quantity = parseFloat($(this).val());

                  if (!isNaN(unit_price) && !isNaN(quantity))
                      total += unit_price * quantity;
              });

              $("#invoice_amount").val(total.toFixed(2));
          });


          $(".fa-times").click(function () {
              $(this).parent().parent().hide("slow");
              $(this).siblings(".destroy").val("true");
              return false;
          });

          $(".add-more-items").click(function () {
              $("input[name='add_more_items']").val(<%= @invoice.payments.length %>);
              $("form.form-horizontal").submit();
          });

      });
  </script>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to 'Invoices', admin_billing_invoices_path(paid: @invoice.paid ? 1 : 0) %></li>
  <% if @invoice.persisted? %>
    <li><%= link_to "Invoice #{@invoice.id}", admin_billing_invoice_path(@invoice) %></li>
    <li class="active">edit</li>
  <% else %>
    <li class="active">new</li>
  <% end %>
<% end %>

app/views/admin/billing/invoices/index.html.erb
<div class="pull-right">
  <%= render 'admin/billing/invoices/group_actions' %>
</div>

<h2>
  <i class="fa fa-file-invoice-dollar"></i> &nbsp;Invoices
</h2>


<% if !params[:uid].blank? || !params[:start_date].blank? || !params[:end_date].blank? %>
  <div class="bs-callout <%= @payments.total_entries == 0 ? "bs-callout-danger" : "bs-callout-info" %>">
    <%= link_to request.url.split('?').first, class: "pull-right btn btn-xs btn-default" do %>
      <i class="fa fa-times"></i> clear filter
    <% end %>
    Found <%= @invoices.total_entries %> records matching search criteria
  </div>
<% end %>


<ul class="nav nav-tabs" style="margin-bottom: 10px;">
  <li class="<%= "active" if params[:paid] == "0" %>">
    <a href="<%= admin_billing_invoices_path(paid: 0) %>"><%= tab_count("Unpaid", Invoice.where(paid: false).count) %></a>
  </li>
  <li class="<%= "active" if params[:paid] == "1" %>">
    <a href="<%= admin_billing_invoices_path(paid: 1) %>"><%= tab_count("Paid", Invoice.where(paid: true).count) %></a>
  </li>
</ul>

<form id="frmBatch" action="" method="post">
  <%= token_tag %>
  <input type="hidden" name="printer_id" value=""/>
  <input type="hidden" name="email_address" value=""/>

  <%= will_paginate @invoices %>
  <table class="table table-striped table-condensed">
    <tr>
      <th><input type="checkbox" id="chkAll"></th>
      <th>ID</th>
      <th>Post Date</th>
      <th>Invoicer</th>
      <th>Invoicee</th>
      <th class="text-right">Amount</th>
      <th class="text-center">Due Date</th>
      <th class="text-center">Paid?</th>
      <th></th>
    </tr>
    <%= render @invoices %>
  </table>
</form>

<%= render 'admin/shared/table_summary', data: @invoices %>


<% content_for :title do %>
  Invoices
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li class="active">Invoices</li>
<% end %>