config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    namespace :billing do
      get 'billing_arrangements/index'
      get 'billing_arrangements/edit'
    end
  end
  namespace :admin do
  namespace :billing do
    get 'credit_memos/index'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'credit_memos/edit'
    end
  end

  namespace :admin do
  namespace :billing do
    get 'cc_transactions/index'
    end
  end

  namespace :admin do
    
    namespace :billing do
      post 'email_invoice' => 'invoices#email'
      post 'invoices_print_batch' => 'invoices#print_batch'
      post 'invoices_email_batch' => 'invoices#email_batch'
      post 'invoices_update_status_batch' => 'invoices#update_status_batch'
      
			resources :billing_arrangements do 
				member do
					get 'update_prices'
				end
			end
      resources :cc_transactions
      resources :service_types
      resources :packages do
        member do
          get 'details' => 'packages#details'
          post 'details' => 'packages#update_details'
        end
      end
      resources :package_details
      resources :user_packages do
        member do
          get 'services'
          get 'add_service'
        end
      end
      resources :user_services
      resources :payment_methods
      resources :invoices do 
        member do 
          get 'print'
          post 'email'
        end
      end
      resources :credit_memos do 
        member do 
          get 'print'
        end
      end
      resources :payments do 
        member do
          get 'refund'
        end
      end
    end
    
  end
  
  namespace :account do
    resources :user_packages
    resources :payments
    resources :payment_methods do
      member do 
        get 'primary'
      end
    end
  end
  
end

app/controllers/account/user_packages_controller.rb
class Account::UserPackagesController < Account::BaseController

  def index
    @user_packages = UserPackage.includes(:package)
                         .where(user_id: session[:user_id], recurr_status: ["A", "D"])
                         .where("recurr_date > ?", Date.today)
  end

  def destroy
    @user_package = UserPackage.find_by(user_id: session[:user_id], id: params[:id])
    @user_package.update_column(:recurr_status, "D")

    flash[:success] = "Your subsciption has been marked for cancellation. It will remain active until #{@user_package.recurr_date} "
    redirect_back(fallback_location: account_user_packages_path)
  end

end

app/controllers/admin/billing/billing_arrangements_controller.rb
class Admin::Billing::BillingArrangementsController < Admin::BaseController

  def index
    authorize BillingArrangement.new
    @billing_arrangements = BillingArrangement.includes(:affiliate, :seller).order(created_at: :desc)

    respond_to do |format|
      format.html { @billing_arrangements = @billing_arrangements.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data BillingArrangement.to_csv(@billing_arrangements) }
    end
  end

  def new
    @billing_arrangement = authorize BillingArrangement.new
    render 'edit'
  end

  def create
    @billing_arrangement = authorize BillingArrangement.new(billing_arrangement_params)

    if @billing_arrangement.save
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def show
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def edit
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
  end

  def update
    @billing_arrangement = authorize BillingArrangement.find(params[:id])

    if @billing_arrangement.update(billing_arrangement_params)
      redirect_to action: :show, id: @billing_arrangement.id
    else
      render 'edit'
    end
  end

  def destroy
    @billing_arrangement = authorize BillingArrangement.find(params[:id])
    @billing_arrangement.destroy

    flash[:notice] = "Billing Arrangement has been deleted."
    redirect_back fallback_location: {action: 'index'}
  end

  def update_prices
    @billing_arrangement = BillingArrangement.find(params[:id])

    ap_list = AffiliateProduct.joins(:product)
                  .where(affiliate_id: @billing_arrangement.seller_id)
                  .where("store_products.fulfiller_id = ?", @billing_arrangement.affiliate_id)

    if @billing_arrangement.percent_of_msrp
      count = ap_list.update_all("store_affiliate_products.price = store_products.msrp * #{@billing_arrangement.percent_of_msrp / 100.0}")
    else
      count = ap_list.update_all("store_affiliate_products.price = store_products.reseller_price")
    end

    flash[:info] = "Pricing updated."
    redirect_to action: :show, id: @billing_arrangement.id
  end

  private

  def billing_arrangement_params
    params.require(:billing_arrangement).permit!
  end

end

app/controllers/admin/billing/cc_transactions_controller.rb
class Admin::Billing::CcTransactionsController < Admin::BaseController

  def index
    authorize CcTransaction.new
    @cc_transactions = CcTransaction.joins(:payment_method)
                           .includes(:payment_method)
                           .order(sort_column + " " + sort_direction)

    @cc_transactions = @cc_transactions.where("created_at > '#{params[:start_date]}'") unless params[:start_date].blank?
    @cc_transactions = @cc_transactions.where("created_at < '#{params[:end_date]}'") unless params[:end_date].blank?

    respond_to do |format|
      format.html { @cc_transactions = @cc_transactions.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data CcTransaction.to_csv(@cc_transactions) }
    end

  end

  def show
    @cc_transaction = authorize CcTransaction.find(params[:id])
  end


  private

  def sort_column
    params[:sort] || "bill_cc_transactions.created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/controllers/admin/billing/credit_memos_controller.rb
class Admin::Billing::CreditMemosController < Admin::BaseController
  def index
    authorize CreditMemo.new
    @credit_memos = CreditMemo.order(created_at: :desc)
                        .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @credit_memo = authorize CreditMemo.new
    render 'edit'
  end

  def create
    @credit_memo = authorize CreditMemo.new(credit_memo_params)

    if @credit_memo.save
      redirect_to action: 'index', notice: 'Credit Memo was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def edit
    @credit_memo = authorize CreditMemo.find(params[:id])
  end

  def update
    @credit_memo = authorize CreditMemo.find(params[:id])

    if @credit_memo.update(credit_memo_params)
      redirect_to action: 'index', notice: 'Credit Memo was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    cm = authorize CreditMemo.find(params[:id])
    cm.destroy
    redirect_to action: 'index', notice: 'Credit Memo has been deleted.'
  end

  def print
    @credit_memo = CreditMemo.find(params[:id])
    authorize @credit_memo, :show?
    render 'print', layout: nil
  end


  private

  def credit_memo_params
    params.require(:credit_memo).permit!
  end

end

app/controllers/admin/billing/invoices_controller.rb
class Admin::Billing::InvoicesController < Admin::BaseController

  def index
    authorize Invoice.new
    @invoices = Invoice.where(paid: params[:paid])
                    .order(post_date: :desc)
                    .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    if params[:affiliate_id]
      @pending_payments = Payment.where(affiliate_id: params[:affiliate_id], invoice_id: nil)
                              .where.not(payable_type: :invoice)
    end

    @invoice = Invoice.new
    5.times { @invoice.payments.build }

    authorize @invoice
    render 'edit'
  end

  def create
    @invoice = authorize Invoice.new(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @invoice.items.length + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully created.'
    else
      5.times { @invoice.payments.build }
      render 'edit'
    end
  end

  def edit
    @invoice = authorize Invoice.find(params[:id])
    @pending_payments = Payment.where(invoice_id: @invoice.id)
                            .where.not(payable_type: :invoice)

    2.times { @invoice.payments.build }
  end

  def update
    @invoice = authorize Invoice.find(params[:id])
    item_count = @invoice.payments.length

    @invoice.assign_attributes(invoice_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      count.times { @invoice.payments.build }
      return render 'edit'
    end

    if @invoice.save(validate: false)
      redirect_to action: 'show', id: @invoice.id, notice: 'Invoice was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @invoice = authorize Invoice.find(params[:id])
  end

  def print
    @invoice = Invoice.find(params[:id])
    render 'print', layout: nil
  end

  def print_batch
    authorize Invoice, :show?

    urls = ''
    token = Cache.setting(Rails.configuration.domain_id, :system, 'Security Token')
    website_url = Cache.setting(Rails.configuration.domain_id, :system, 'Website URL')

    Invoice.where(id: params[:invoice_id]).each do |inv|
      digest = Digest::MD5.hexdigest(inv.id.to_s + token)
      urls += " " + website_url + print_admin_billing_invoice_path(inv, digest: digest)

      # LOG HERE
      inv.logs.create(timestamp: Time.now,
                      user_id: session[:user_id],
                      ip_address: request.remote_ip,
                      event: :printed,
                      data1: params[:printer_id].presence || 'PDF download')
    end

    output_file = "/tmp/#{SecureRandom.hex(6)}.pdf"
    ret = system("wkhtmltopdf -q -s Letter #{urls} #{output_file}")

    #puts ">>>>>>>> " + urls

    unless File.exist?(output_file)
      flash[:error] = "Unable to generate PDF [Debug: #{$?}]"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:printer_id].blank?
      send_file output_file
    else
      printer = Printer.find(params[:printer_id])
      job = printer.print_file(output_file)
      flash[:info] = "Print job submitted to '#{printer.name} [#{printer.location}]'. CUPS JobID: #{job.id}"
      redirect_back(fallback_location: admin_billing_invoices_path)
    end
  end

  def email
    @invoice = Invoice.find(params[:invoice_id])

    EmailInvoiceJob.perform_later(@invoice.id, params[:email])
    @invoice.logs.create(user_id: session[:user_id], ip_address: request.remote_ip, event: 'emailed', data1: params[:email])

    flash[:info] = "Invoice ##{@invoice.id} has been emailed to #{params[:email]}"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def email_batch

    if params[:email_address].blank?
      flash[:error] = "Please specify an email address"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    if params[:invoice_id].length == 0
      flash[:error] = "Please invoices to email"
      return redirect_back(fallback_location: admin_billing_invoices_path)
    end

    begin
      InvoiceMailer.batch(params[:invoice_id], session[:user_id], params[:email_address], request.remote_ip).deliver_now
      flash[:success] = "#{params[:invoice_id].length} invoice(s) were mailed to '#{params[:email_address]}'"
    rescue => e
      flash[:error] = e.message
    end

    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  def update_status_batch
    authorize Invoice, :update?
    list = Invoice.where(id: params[:invoice_id])

    list.each do |invoice|
      invoice.update(paid: params[:paid] == "true")
      #log
    end

    flash[:info] = "#{list.length} invoices updated"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end

  def destroy
    @invoice = authorize Invoice.find(params[:id])

    Payment.where(invoice_id: @invoice.id).update_all(invoice_id: nil)
    @invoice.destroy

    flash.now[:success] = "Invoice ##{@invoice.id} has been deleted"
    redirect_back(fallback_location: admin_billing_invoices_path)
  end


  private

  def invoice_params
    params.require(:invoice).permit!
  end

end

app/controllers/admin/billing/package_details_controller.rb
class Admin::Billing::PackageDetailsController < Admin::BaseController

  def new
    @package_detail = PackageDetail.new package_id: params[:package_id]
    render 'edit'
  end

  def create
    @package_detail = PackageDetail.new(package_detail_params)

    if @package_detail.save
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def edit
    @package_detail = PackageDetail.find(params[:id])
  end

  def update
    @package_detail = PackageDetail.find(params[:id])

    if @package_detail.update(package_detail_params)
      redirect_to details_admin_billing_package_path(@package_detail.package)
    else
      render 'edit'
    end
  end

  def destroy
    @package_detail = PackageDetail.find(params[:id])
    @package_detail.destroy
    redirect_to action: 'index', notice: 'Package detail has been deleted.'
  end

  def details
    @package = PackageDetail.find(params[:id])
  end


  private

  def package_detail_params
    params.require(:package_detail).permit!
  end

end

app/controllers/admin/billing/packages_controller.rb
class Admin::Billing::PackagesController < Admin::BaseController

  def index
    authorize Package.new
    @packages = Package.where(domain_id: cookies[:domain_id])

    respond_to do |format|
      format.html { @packages = @packages.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Package.to_csv(@packages) }
    end
  end

  def new
    @package = authorize Package.new(name: 'New Package', sort: 9, trial_days: 0)
    render 'edit'
  end

  def create
    @package = authorize Package.new(package_params)
    @package.domain_id = cookies[:domain_id]

    if @package.save
      redirect_to action: 'index', notice: 'Package was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @package = authorize Package.includes(:details, [details: :service_type]).find(params[:id])
  end

  def edit
    @package = authorize Package.find(params[:id])
  end

  def update
    @package = authorize Package.find(params[:id])

    if @package.update(package_params)
      redirect_to action: 'index', notice: 'Package was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @package = authorize Package.find(params[:id])
    @package.destroy
    redirect_to action: 'index', notice: 'Package has been deleted.'
  end


  def details
    @package = Package.find(params[:id])
    authorize @package, :show?
  end


  private

  def package_params
    params.require(:package).permit!
  end

end

app/controllers/admin/billing/payment_methods_controller.rb
class Admin::Billing::PaymentMethodsController < Admin::BaseController

  def index
    authorize PaymentMethod.new
    @payment_methods = PaymentMethod.includes(:user)

    respond_to do |format|
      format.html { @payment_methods = @payment_methods.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data PaymentMethod.to_csv(@payment_methods) }
    end
  end

  def show
    @payment_method = authorize PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = authorize PaymentMethod.new(user_id: params[:user_id])
  end

  def create
    @payment_method = authorize PaymentMethod.new(payment_method_params)
    @payment_method.status = 'A'

    if @payment_method.save
      flash[:notice] = 'Payment Method was successfully created.'
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def destroy
    pm = authorize PaymentMethod.find(params[:id])
    pm.destroy

    # if there is only one remaining payment_method, make it the default
    if PaymentMethod.where(user_id: pm.user_id).count == 1
      PaymentMethod.where(user_id: pm_user_id).update_all(default: true)
    end

    redirect_to action: 'index'
  end


  private

  def payment_method_params
    params.require(:payment_method).permit!
  end

end

app/controllers/admin/billing/user_services_controller.rb
class Admin::Billing::UserServicesController < Admin::BaseController

  def new
    @user_service = UserService.new user_package_id: params[:user_package_id]
    render 'edit'
  end

  def create
    @user_service = UserService.new(user_service_params)

    if @user_service.save
      redirect_to services_admin_billing_user_package_path(@user_service.user_package_id)
    else
      render 'edit'
    end
  end

  def edit
    @user_service = UserService.find(params[:id])
  end

  def update
    @user_service = UserService.find(params[:id])

    if @user_service.update(user_service_params)
      redirect_to services_admin_billing_user_package_path(@user_service.user_package_id)
    else
      render 'edit'
    end
  end

  def destroy
    @user_service = UserService.find(params[:id])
    @user_service.destroy
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def user_service_params
    params.require(:user_service).permit!
  end

end

app/helpers/admin/billing/billing_arrangements_helper.rb
module Admin::Billing::BillingArrangementsHelper
end

app/views/admin/billing/user_packages/edit.html.erb
<h2>[<%= @user_package.id %>] <%= @user_package.user %></h2>
<hr>


<%= render 'admin/shared/error_messages', object: @user_package %>

<%= simple_form_for [:admin, :billing, @user_package] do |f| %>

  <div class="row">
    <div class="col-md-6">
      <%= f.association :user %>
      <%= f.association :package %>
      <%= f.input :amount %>
      <%= f.input :rate %>
    </div>
    <div class="col-md-6">
      <%= f.input :recurr_date, as: :datepicker %>
      <%= f.input :recurr_status, collection: ['A', 'P', 'D', 'I'] %>
      <%= f.input :bill_attempts %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-condensed table-striped">
        <tr>
          <th>Code</th>
          <th>Service</th>
          <th>Included</th>
          <th>Used</th>
          <th>Rate</th>
        </tr>

        <%= f.fields_for :services do |sf| %>
          <% svc = @user_package.services[sf.index] %>
          <tr>
            <td><%= svc.service_type.code %></td>
            <td><%= svc.service_type.name %></td>
            <td><%= sf.input_field :quantity %></td>
            <td><%= sf.input_field :used %></td>
            <td><%= sf.input_field :rate %> / <%= svc.service_type.bill_frequency %></td>
          </tr>
        <% end %>
      </table>

      <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>
    </div>
  </div>
<% end %>



<% content_for :title do %>
  User Subscription #<%= @user_package.id %>
<% end %>



<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to "User Subscriptions", admin_billing_user_packages_path %></li>
  <% if @user_package.persisted? %>
    <li><%= link_to "User Subscription ##{@user_package.id}", admin_billing_user_package_path(@user_package) %></li>
    <li class="active">edit</li>
  <% else %>
    <li>new</li>
  <% end %>
<% end %>

app/views/admin/billing/user_packages/index.html.erb
<%= link_to new_admin_billing_user_package_path, class: 'btn btn-sm btn-default pull-right' do %>
  <i class="fa fa-plus"></i> New subscription
<% end %>
<h2><i class="fa fa-user-clock"></i> User Subscriptions</h2>


<table class="table table-striped table-condensed">
  <tr>
    <th>ID</th>
    <th>User</th>
    <th>Package</th>
    <th class="text-right">Rate</th>
    <th class="text-center">Recurr Date</th>
    <th class="text-center">Bill Attempts</th>
    <th class="text-center">Status</th>
    <th></th>
  </tr>
  <% @user_packages.each do |up| %>
    <tr>
      <td><%= link_to up.id.to_s, admin_billing_user_package_path(up) %></td>
      <td><%= link_to up.user.name, admin_system_user_path(up.user) %></td>
      <td><%= link_to up.package.name, admin_billing_package_path(up.package) %></td>
      <td class="text-right"><%= number_to_currency(up.total_price) %></td>
      <td class="text-center"><%= sysdate up.recurr_date %></td>
      <td class="text-center"><%= up.bill_attempts %></td>
      <td class="text-center"><%= up.recurr_status %></td>
      <td class="text-right">
        <%= link_to "edit", edit_admin_billing_user_package_path(up) %> &nbsp;
        <%= link_to "delete",
                    {action: "destroy", id: up.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @user_packages %>



<% content_for :title do %>
  User Subscriptions
<% end %>



<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li class="active">User Subscriptions</li>
<% end %>

app/views/admin/billing/user_packages/services.html.erb
<h2>User Subscription #<%= @user_package.id %></h2>


<%= link_to "add new service", new_admin_billing_user_service_path(user_package_id: @user_package.id), class: 'btn btn-sm btn-default pull-right' %>

<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_billing_user_package_path(@user_package) %></li>
  <li class="active"><a href="#">Services</a></li>
</ul>

<table class="table table-striped table-condensed">
  <tr>
    <th>Service Type</th>
    <th>Included Quantity</th>
    <th>Used Quantity</th>
    <th>Rate</th>
    <th></th>
  </tr>
  <% @user_package.services.each do |svc| %>
    <tr>
      <td><%= svc.service_type.name %></td>
      <td><%= svc.quantity %></td>
      <td><%= svc.used %></td>
      <td>
        <% if svc.rate %>
          <%= number_to_currency(svc.rate) %>
        <% else %>
          - included -
        <% end %>
      </td>
      <td>
        <%= link_to "edit", edit_admin_billing_user_service_path(svc) %> &nbsp;
        <%= link_to "delete",
                    {action: "destroy", controller: 'user_services', id: svc.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>



<%= content_for :title do %>
  User Subscription #<%= @user_package.id %>
<% end %>


<% content_for :menu do
  render "admin/shared/billing_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to "User Subscriptions", admin_billing_user_packages_path %></li>
  <li><%= link_to "User Subscription ##{@user_package.id}", admin_billing_user_package_path(@user_package) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/billing/user_packages/show.html.erb
<div class="pull-right">
  <h3 class="light" style="display: inline-block; margin: 8px 30px 0 0">Total: <%= number_to_currency @user_package.total_price %>
    / mo.</h3>
  <%= link_to "edit", edit_admin_billing_user_package_path(@user_package), class: "btn btn-sm btn-default" %>
</div>
<h2>[<%= @user_package.id %>] <%= @user_package.user %></h2>
<hr/>

<div class="row">
  <div class="col-md-6">
    <table class="table table-condensed table-bordered summary">
      <%= obj_property(@user_package, :user) { |x| link_to x.name, admin_system_user_path(x) } %>
      <%= obj_property @user_package, :package %>
      <%= obj_property @user_package, :recurr_status %>
      <%= obj_property @user_package, :recurr_date %>
    </table>
  </div>

  <div class="col-md-6">
    <table class="table table-condensed table-bordered summary">
      <%= obj_property @user_package, :rate, label: "Base rate" %>
      <%= obj_property(@user_package, :total_price, label: "With extras") %>
      <%= obj_property(@user_package, :payments, label: "Balance due") { |x| x.sum(:amount) } %>
    </table>
  </div>
</div>


<div class="row">
  <div class="col-md-8">
    <h4>Included Services</h4>
    <table class="table table-striped table-condensed">
      <tr>
        <th>Code</th>
        <th class="text-center">Included</th>
        <th class="text-center">Used</th>
        <th class="text-center">Rate</th>
        <th>Service Type</th>
        <th></th>
      </tr>
      <% included_svcs = []
         @user_package.services.each do |svc|
           included_svcs << svc.service_type.id
      %>
        <tr>
          <td><%= svc.service_type.code %></td>

          <td class="text-center"><%= number_with_delimiter svc.quantity.round %></td>
          <td class="text-center"><%= number_with_delimiter svc.used.round %></td>
          <td class="text-center">
            <% if svc.rate %>
              <%= number_to_currency(svc.rate) %> / <%= svc.service_type.bill_frequency.downcase %>
            <% else %>
              - included -
            <% end %>
          </td>
          <td>
            <%= svc.service_type.name %>
            <% if svc.items.length > 0 %>
              <small>
                &raquo;
                <% svc.items.collect { |x| x.item_id }.join(", ") %>
              </small>
            <% end %>
          </td>
          <td><%= link_to "- remove",
                          {action: "destroy", controller: 'user_services', id: svc.id},
                          method: :delete,
                          data: {confirm: "Is it OK to remove #{svc.service_type.code} service?"} %></td>
        </tr>
      <% end %>
    </table>


    <h4>Payments</h4>
    <table class="table table-striped table-condensed">
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Memo</th>
        <th>Amount</th>
      </tr>
      <% @user_package.payments.order('created_at DESC').each do |payment| %>
        <tr>
          <td><%= payment.id %></td>
          <td><%= systime payment.created_at %></td>
          <td><%= payment.memo %></td>
          <td><%= number_to_currency(payment.amount) %></td>
        </tr>
      <% end %>
    </table>

  </div>

  <div class="col-md-4">
    <h4>Available</h4>
    <% svc_list = ServiceType.where.not(id: included_svcs) %>
    <table class="table table-striped table-condensed">
      <tr>
        <th>Code</th>
        <th>Description</th>
        <th>&nbsp;</th>
      </tr>
      <% svc_list.each do |svc| %>
        <tr>
          <td><%= svc.code %></td>
          <td><%= svc.name %></td>
          <td><%= link_to "+ add", add_service_admin_billing_user_package_path(@user_package, service_type_id: svc.id) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>  <!-- row -->


<% content_for :title do %>
  <%= "Subscription ##{@user_package.id}" %>
<% end %>


<% content_for :menu do
  render "admin/shared/billing_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Billing</a></li>
  <li><%= link_to "Subscriptions", admin_billing_user_packages_path %></li>
  <li class="active">Subscription #<%= @user_package.id %></li>
<% end %>